/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  boolean,
  jsonb,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_pages_blocks_cta_ctas_variant = pgEnum(
  "enum_pages_blocks_cta_ctas_variant",
  ["primary", "secondary"],
);
export const enum_pages_blocks_cta_ctas_icon = pgEnum(
  "enum_pages_blocks_cta_ctas_icon",
  ["none", "externalLink", "discord", "terminal"],
);
export const enum_pages_blocks_cta_align = pgEnum(
  "enum_pages_blocks_cta_align",
  ["center", "left"],
);
export const enum_pages_blocks_knowledgebase_index_variant = pgEnum(
  "enum_pages_blocks_knowledgebase_index_variant",
  ["standalone", "sidebar"],
);
export const enum_pages_blocks_quick_stats_stats_icon = pgEnum(
  "enum_pages_blocks_quick_stats_stats_icon",
  [
    "Antenna",
    "Battery",
    "Bluetooth",
    "Camera",
    "Cpu",
    "EthernetPort",
    "ExternalLink",
    "Gamepad2",
    "Gpu",
    "HardDrive",
    "Heart",
    "Keyboard",
    "MemoryStick",
    "Radio",
    "Terminal",
    "Usb",
    "Wifi",
    "Zap",
  ],
);
export const enum_pages_blocks_quick_stats_stats_color = pgEnum(
  "enum_pages_blocks_quick_stats_stats_color",
  ["cyan", "blue", "purple", "green", "yellow", "orange", "red", "pink"],
);
export const enum_pages_blocks_detail_stat_icon = pgEnum(
  "enum_pages_blocks_detail_stat_icon",
  [
    "Antenna",
    "Battery",
    "Bluetooth",
    "Camera",
    "Cpu",
    "EthernetPort",
    "ExternalLink",
    "Gamepad2",
    "Gpu",
    "HardDrive",
    "Heart",
    "Keyboard",
    "MemoryStick",
    "Radio",
    "Terminal",
    "Usb",
    "Wifi",
    "Zap",
  ],
);
export const enum_pages_blocks_detail_stat_color = pgEnum(
  "enum_pages_blocks_detail_stat_color",
  ["cyan", "blue", "purple", "green", "yellow", "orange", "red", "pink"],
);
export const enum_pages_blocks_cta_container_ctas_variant = pgEnum(
  "enum_pages_blocks_cta_container_ctas_variant",
  ["primary", "secondary"],
);
export const enum_pages_blocks_cta_container_ctas_icon = pgEnum(
  "enum_pages_blocks_cta_container_ctas_icon",
  ["none", "externalLink", "discord", "terminal"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const pages_blocks_hero = pgTable(
  "pages_blocks_hero",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    titlePrimary: varchar("title_primary").notNull().default("JetDeck"),
    titleSecondary: varchar("title_secondary").notNull().default("SCOUT"),
    tagline: varchar("tagline").default("Smart Cyber Ops Utility Tool"),
    subtagline: varchar("subtagline"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_hero_order_idx").on(columns._order),
    index("pages_blocks_hero_parent_id_idx").on(columns._parentID),
    index("pages_blocks_hero_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_hero_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_single_image = pgTable(
  "pages_blocks_single_image",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    constrainWidth: boolean("constrain_width").default(false),
    caption: varchar("caption"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_single_image_order_idx").on(columns._order),
    index("pages_blocks_single_image_parent_id_idx").on(columns._parentID),
    index("pages_blocks_single_image_path_idx").on(columns._path),
    index("pages_blocks_single_image_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_single_image_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_photo_carousel_images = pgTable(
  "pages_blocks_photo_carousel_images",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("pages_blocks_photo_carousel_images_order_idx").on(columns._order),
    index("pages_blocks_photo_carousel_images_parent_id_idx").on(
      columns._parentID,
    ),
    index("pages_blocks_photo_carousel_images_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_photo_carousel.id],
      name: "pages_blocks_photo_carousel_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_photo_carousel = pgTable(
  "pages_blocks_photo_carousel",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    caption: varchar("caption"),
    constrainWidth: boolean("constrain_width").default(true),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_photo_carousel_order_idx").on(columns._order),
    index("pages_blocks_photo_carousel_parent_id_idx").on(columns._parentID),
    index("pages_blocks_photo_carousel_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_photo_carousel_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_ctas = pgTable(
  "pages_blocks_cta_ctas",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
    variant: enum_pages_blocks_cta_ctas_variant("variant")
      .notNull()
      .default("primary"),
    icon: enum_pages_blocks_cta_ctas_icon("icon")
      .notNull()
      .default("externalLink"),
  },
  (columns) => [
    index("pages_blocks_cta_ctas_order_idx").on(columns._order),
    index("pages_blocks_cta_ctas_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_cta.id],
      name: "pages_blocks_cta_ctas_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta = pgTable(
  "pages_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    align: enum_pages_blocks_cta_align("align").notNull().default("center"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_cta_order_idx").on(columns._order),
    index("pages_blocks_cta_parent_id_idx").on(columns._parentID),
    index("pages_blocks_cta_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_text_block_paragraphs = pgTable(
  "pages_blocks_text_block_paragraphs",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("pages_blocks_text_block_paragraphs_order_idx").on(columns._order),
    index("pages_blocks_text_block_paragraphs_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_text_block.id],
      name: "pages_blocks_text_block_paragraphs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_text_block = pgTable(
  "pages_blocks_text_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_text_block_order_idx").on(columns._order),
    index("pages_blocks_text_block_parent_id_idx").on(columns._parentID),
    index("pages_blocks_text_block_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_text_block_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_rich_text = pgTable(
  "pages_blocks_rich_text",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    content: jsonb("content").notNull(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_rich_text_order_idx").on(columns._order),
    index("pages_blocks_rich_text_parent_id_idx").on(columns._parentID),
    index("pages_blocks_rich_text_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_rich_text_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_knowledgebase_index = pgTable(
  "pages_blocks_knowledgebase_index",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading").default("Knowledgebase"),
    intro: varchar("intro"),
    variant: enum_pages_blocks_knowledgebase_index_variant("variant")
      .notNull()
      .default("standalone"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_knowledgebase_index_order_idx").on(columns._order),
    index("pages_blocks_knowledgebase_index_parent_id_idx").on(
      columns._parentID,
    ),
    index("pages_blocks_knowledgebase_index_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_knowledgebase_index_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_file_download = pgTable(
  "pages_blocks_file_download",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    url: varchar("url").notNull(),
    description: varchar("description").notNull(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_file_download_order_idx").on(columns._order),
    index("pages_blocks_file_download_parent_id_idx").on(columns._parentID),
    index("pages_blocks_file_download_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_file_download_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_quick_stats_stats = pgTable(
  "pages_blocks_quick_stats_stats",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_pages_blocks_quick_stats_stats_icon("icon").notNull(),
    color: enum_pages_blocks_quick_stats_stats_color("color").notNull(),
    value: varchar("value").notNull(),
    label: varchar("label").notNull(),
  },
  (columns) => [
    index("pages_blocks_quick_stats_stats_order_idx").on(columns._order),
    index("pages_blocks_quick_stats_stats_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_quick_stats.id],
      name: "pages_blocks_quick_stats_stats_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_quick_stats = pgTable(
  "pages_blocks_quick_stats",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_quick_stats_order_idx").on(columns._order),
    index("pages_blocks_quick_stats_parent_id_idx").on(columns._parentID),
    index("pages_blocks_quick_stats_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_quick_stats_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_detail_stat_lines = pgTable(
  "pages_blocks_detail_stat_lines",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("pages_blocks_detail_stat_lines_order_idx").on(columns._order),
    index("pages_blocks_detail_stat_lines_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_detail_stat.id],
      name: "pages_blocks_detail_stat_lines_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_detail_stat = pgTable(
  "pages_blocks_detail_stat",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    icon: enum_pages_blocks_detail_stat_icon("icon").default("Cpu"),
    color: enum_pages_blocks_detail_stat_color("color").default("cyan"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_detail_stat_order_idx").on(columns._order),
    index("pages_blocks_detail_stat_parent_id_idx").on(columns._parentID),
    index("pages_blocks_detail_stat_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_detail_stat_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_specs_table_tabs_rows = pgTable(
  "pages_blocks_specs_table_tabs_rows",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    value: varchar("value").notNull(),
  },
  (columns) => [
    index("pages_blocks_specs_table_tabs_rows_order_idx").on(columns._order),
    index("pages_blocks_specs_table_tabs_rows_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_specs_table_tabs.id],
      name: "pages_blocks_specs_table_tabs_rows_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_specs_table_tabs = pgTable(
  "pages_blocks_specs_table_tabs",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    title: varchar("title").notNull(),
  },
  (columns) => [
    index("pages_blocks_specs_table_tabs_order_idx").on(columns._order),
    index("pages_blocks_specs_table_tabs_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_specs_table.id],
      name: "pages_blocks_specs_table_tabs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_specs_table = pgTable(
  "pages_blocks_specs_table",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    heading: varchar("heading").default("Technical Specifications"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_specs_table_order_idx").on(columns._order),
    index("pages_blocks_specs_table_parent_id_idx").on(columns._parentID),
    index("pages_blocks_specs_table_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_specs_table_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_container_paragraphs = pgTable(
  "pages_blocks_cta_container_paragraphs",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("pages_blocks_cta_container_paragraphs_order_idx").on(columns._order),
    index("pages_blocks_cta_container_paragraphs_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_cta_container.id],
      name: "pages_blocks_cta_container_paragraphs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_container_ctas = pgTable(
  "pages_blocks_cta_container_ctas",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
    variant: enum_pages_blocks_cta_container_ctas_variant("variant")
      .notNull()
      .default("primary"),
    icon: enum_pages_blocks_cta_container_ctas_icon("icon")
      .notNull()
      .default("externalLink"),
  },
  (columns) => [
    index("pages_blocks_cta_container_ctas_order_idx").on(columns._order),
    index("pages_blocks_cta_container_ctas_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_cta_container.id],
      name: "pages_blocks_cta_container_ctas_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_container = pgTable(
  "pages_blocks_cta_container",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull().default("Ready to Join the Revolution?"),
    subtext: varchar("subtext"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_cta_container_order_idx").on(columns._order),
    index("pages_blocks_cta_container_parent_id_idx").on(columns._parentID),
    index("pages_blocks_cta_container_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_cta_container_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    path: varchar("path"),
    showNavigation: boolean("show_navigation").default(true),
    showInNav: boolean("show_in_nav").default(false),
    navLabel: varchar("nav_label"),
    navOrder: numeric("nav_order", { mode: "number" }).default(0),
    isKnowledgebasePage: boolean("is_knowledgebase_page").default(false),
    knowledgebaseLabel: varchar("knowledgebase_label"),
    knowledgebaseDescription: varchar("knowledgebase_description"),
    knowledgebaseParent: integer("knowledgebase_parent_id").references(
      (): AnyPgColumn => pages.id,
      {
        onDelete: "set null",
      },
    ),
    knowledgebaseOrder: numeric("knowledgebase_order", {
      mode: "number",
    }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("pages_path_idx").on(columns.path),
    index("pages_knowledgebase_parent_idx").on(columns.knowledgebaseParent),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    pagesID: integer("pages_id"),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_nav_links = pgTable(
  "site_settings_nav_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("site_settings_nav_links_order_idx").on(columns._order),
    index("site_settings_nav_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_nav_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns_links = pgTable(
  "site_settings_footer_columns_links",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("site_settings_footer_columns_links_order_idx").on(columns._order),
    index("site_settings_footer_columns_links_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_footer_columns.id],
      name: "site_settings_footer_columns_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns = pgTable(
  "site_settings_footer_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
  },
  (columns) => [
    index("site_settings_footer_columns_order_idx").on(columns._order),
    index("site_settings_footer_columns_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_footer_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  navBrandLabel: varchar("nav_brand_label").default("JetDeck SCOUT"),
  disablePageCache: boolean("disable_page_cache").default(false),
  footerLine1: varchar("footer_line1").default("> JetDeck SCOUT © 2026"),
  footerLine2: varchar("footer_line2").default(
    "Built for hackers, makers, and dreamers.",
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_pages_blocks_hero = relations(
  pages_blocks_hero,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_hero._parentID],
      references: [pages.id],
      relationName: "_blocks_hero",
    }),
  }),
);
export const relations_pages_blocks_single_image = relations(
  pages_blocks_single_image,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_single_image._parentID],
      references: [pages.id],
      relationName: "_blocks_singleImage",
    }),
    image: one(media, {
      fields: [pages_blocks_single_image.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_pages_blocks_photo_carousel_images = relations(
  pages_blocks_photo_carousel_images,
  ({ one }) => ({
    _parentID: one(pages_blocks_photo_carousel, {
      fields: [pages_blocks_photo_carousel_images._parentID],
      references: [pages_blocks_photo_carousel.id],
      relationName: "images",
    }),
    image: one(media, {
      fields: [pages_blocks_photo_carousel_images.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_pages_blocks_photo_carousel = relations(
  pages_blocks_photo_carousel,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_photo_carousel._parentID],
      references: [pages.id],
      relationName: "_blocks_photoCarousel",
    }),
    images: many(pages_blocks_photo_carousel_images, {
      relationName: "images",
    }),
  }),
);
export const relations_pages_blocks_cta_ctas = relations(
  pages_blocks_cta_ctas,
  ({ one }) => ({
    _parentID: one(pages_blocks_cta, {
      fields: [pages_blocks_cta_ctas._parentID],
      references: [pages_blocks_cta.id],
      relationName: "ctas",
    }),
  }),
);
export const relations_pages_blocks_cta = relations(
  pages_blocks_cta,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cta._parentID],
      references: [pages.id],
      relationName: "_blocks_cta",
    }),
    ctas: many(pages_blocks_cta_ctas, {
      relationName: "ctas",
    }),
  }),
);
export const relations_pages_blocks_text_block_paragraphs = relations(
  pages_blocks_text_block_paragraphs,
  ({ one }) => ({
    _parentID: one(pages_blocks_text_block, {
      fields: [pages_blocks_text_block_paragraphs._parentID],
      references: [pages_blocks_text_block.id],
      relationName: "paragraphs",
    }),
  }),
);
export const relations_pages_blocks_text_block = relations(
  pages_blocks_text_block,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_text_block._parentID],
      references: [pages.id],
      relationName: "_blocks_textBlock",
    }),
    paragraphs: many(pages_blocks_text_block_paragraphs, {
      relationName: "paragraphs",
    }),
  }),
);
export const relations_pages_blocks_rich_text = relations(
  pages_blocks_rich_text,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_rich_text._parentID],
      references: [pages.id],
      relationName: "_blocks_richText",
    }),
  }),
);
export const relations_pages_blocks_knowledgebase_index = relations(
  pages_blocks_knowledgebase_index,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_knowledgebase_index._parentID],
      references: [pages.id],
      relationName: "_blocks_knowledgebaseIndex",
    }),
  }),
);
export const relations_pages_blocks_file_download = relations(
  pages_blocks_file_download,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_file_download._parentID],
      references: [pages.id],
      relationName: "_blocks_fileDownload",
    }),
  }),
);
export const relations_pages_blocks_quick_stats_stats = relations(
  pages_blocks_quick_stats_stats,
  ({ one }) => ({
    _parentID: one(pages_blocks_quick_stats, {
      fields: [pages_blocks_quick_stats_stats._parentID],
      references: [pages_blocks_quick_stats.id],
      relationName: "stats",
    }),
  }),
);
export const relations_pages_blocks_quick_stats = relations(
  pages_blocks_quick_stats,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_quick_stats._parentID],
      references: [pages.id],
      relationName: "_blocks_quickStats",
    }),
    stats: many(pages_blocks_quick_stats_stats, {
      relationName: "stats",
    }),
  }),
);
export const relations_pages_blocks_detail_stat_lines = relations(
  pages_blocks_detail_stat_lines,
  ({ one }) => ({
    _parentID: one(pages_blocks_detail_stat, {
      fields: [pages_blocks_detail_stat_lines._parentID],
      references: [pages_blocks_detail_stat.id],
      relationName: "lines",
    }),
  }),
);
export const relations_pages_blocks_detail_stat = relations(
  pages_blocks_detail_stat,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_detail_stat._parentID],
      references: [pages.id],
      relationName: "_blocks_detailStat",
    }),
    lines: many(pages_blocks_detail_stat_lines, {
      relationName: "lines",
    }),
  }),
);
export const relations_pages_blocks_specs_table_tabs_rows = relations(
  pages_blocks_specs_table_tabs_rows,
  ({ one }) => ({
    _parentID: one(pages_blocks_specs_table_tabs, {
      fields: [pages_blocks_specs_table_tabs_rows._parentID],
      references: [pages_blocks_specs_table_tabs.id],
      relationName: "rows",
    }),
  }),
);
export const relations_pages_blocks_specs_table_tabs = relations(
  pages_blocks_specs_table_tabs,
  ({ one, many }) => ({
    _parentID: one(pages_blocks_specs_table, {
      fields: [pages_blocks_specs_table_tabs._parentID],
      references: [pages_blocks_specs_table.id],
      relationName: "tabs",
    }),
    rows: many(pages_blocks_specs_table_tabs_rows, {
      relationName: "rows",
    }),
  }),
);
export const relations_pages_blocks_specs_table = relations(
  pages_blocks_specs_table,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_specs_table._parentID],
      references: [pages.id],
      relationName: "_blocks_specsTable",
    }),
    tabs: many(pages_blocks_specs_table_tabs, {
      relationName: "tabs",
    }),
  }),
);
export const relations_pages_blocks_cta_container_paragraphs = relations(
  pages_blocks_cta_container_paragraphs,
  ({ one }) => ({
    _parentID: one(pages_blocks_cta_container, {
      fields: [pages_blocks_cta_container_paragraphs._parentID],
      references: [pages_blocks_cta_container.id],
      relationName: "paragraphs",
    }),
  }),
);
export const relations_pages_blocks_cta_container_ctas = relations(
  pages_blocks_cta_container_ctas,
  ({ one }) => ({
    _parentID: one(pages_blocks_cta_container, {
      fields: [pages_blocks_cta_container_ctas._parentID],
      references: [pages_blocks_cta_container.id],
      relationName: "ctas",
    }),
  }),
);
export const relations_pages_blocks_cta_container = relations(
  pages_blocks_cta_container,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cta_container._parentID],
      references: [pages.id],
      relationName: "_blocks_ctaContainer",
    }),
    paragraphs: many(pages_blocks_cta_container_paragraphs, {
      relationName: "paragraphs",
    }),
    ctas: many(pages_blocks_cta_container_ctas, {
      relationName: "ctas",
    }),
  }),
);
export const relations_pages = relations(pages, ({ one, many }) => ({
  knowledgebaseParent: one(pages, {
    fields: [pages.knowledgebaseParent],
    references: [pages.id],
    relationName: "knowledgebaseParent",
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: "_blocks_hero",
  }),
  _blocks_singleImage: many(pages_blocks_single_image, {
    relationName: "_blocks_singleImage",
  }),
  _blocks_photoCarousel: many(pages_blocks_photo_carousel, {
    relationName: "_blocks_photoCarousel",
  }),
  _blocks_cta: many(pages_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_textBlock: many(pages_blocks_text_block, {
    relationName: "_blocks_textBlock",
  }),
  _blocks_richText: many(pages_blocks_rich_text, {
    relationName: "_blocks_richText",
  }),
  _blocks_knowledgebaseIndex: many(pages_blocks_knowledgebase_index, {
    relationName: "_blocks_knowledgebaseIndex",
  }),
  _blocks_fileDownload: many(pages_blocks_file_download, {
    relationName: "_blocks_fileDownload",
  }),
  _blocks_quickStats: many(pages_blocks_quick_stats, {
    relationName: "_blocks_quickStats",
  }),
  _blocks_detailStat: many(pages_blocks_detail_stat, {
    relationName: "_blocks_detailStat",
  }),
  _blocks_specsTable: many(pages_blocks_specs_table, {
    relationName: "_blocks_specsTable",
  }),
  _blocks_ctaContainer: many(pages_blocks_cta_container, {
    relationName: "_blocks_ctaContainer",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_nav_links = relations(
  site_settings_nav_links,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_nav_links._parentID],
      references: [site_settings.id],
      relationName: "navLinks",
    }),
  }),
);
export const relations_site_settings_footer_columns_links = relations(
  site_settings_footer_columns_links,
  ({ one }) => ({
    _parentID: one(site_settings_footer_columns, {
      fields: [site_settings_footer_columns_links._parentID],
      references: [site_settings_footer_columns.id],
      relationName: "links",
    }),
  }),
);
export const relations_site_settings_footer_columns = relations(
  site_settings_footer_columns,
  ({ one, many }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_footer_columns._parentID],
      references: [site_settings.id],
      relationName: "footerColumns",
    }),
    links: many(site_settings_footer_columns_links, {
      relationName: "links",
    }),
  }),
);
export const relations_site_settings = relations(site_settings, ({ many }) => ({
  navLinks: many(site_settings_nav_links, {
    relationName: "navLinks",
  }),
  footerColumns: many(site_settings_footer_columns, {
    relationName: "footerColumns",
  }),
}));

type DatabaseSchema = {
  enum_pages_blocks_cta_ctas_variant: typeof enum_pages_blocks_cta_ctas_variant;
  enum_pages_blocks_cta_ctas_icon: typeof enum_pages_blocks_cta_ctas_icon;
  enum_pages_blocks_cta_align: typeof enum_pages_blocks_cta_align;
  enum_pages_blocks_knowledgebase_index_variant: typeof enum_pages_blocks_knowledgebase_index_variant;
  enum_pages_blocks_quick_stats_stats_icon: typeof enum_pages_blocks_quick_stats_stats_icon;
  enum_pages_blocks_quick_stats_stats_color: typeof enum_pages_blocks_quick_stats_stats_color;
  enum_pages_blocks_detail_stat_icon: typeof enum_pages_blocks_detail_stat_icon;
  enum_pages_blocks_detail_stat_color: typeof enum_pages_blocks_detail_stat_color;
  enum_pages_blocks_cta_container_ctas_variant: typeof enum_pages_blocks_cta_container_ctas_variant;
  enum_pages_blocks_cta_container_ctas_icon: typeof enum_pages_blocks_cta_container_ctas_icon;
  users_sessions: typeof users_sessions;
  users: typeof users;
  pages_blocks_hero: typeof pages_blocks_hero;
  pages_blocks_single_image: typeof pages_blocks_single_image;
  pages_blocks_photo_carousel_images: typeof pages_blocks_photo_carousel_images;
  pages_blocks_photo_carousel: typeof pages_blocks_photo_carousel;
  pages_blocks_cta_ctas: typeof pages_blocks_cta_ctas;
  pages_blocks_cta: typeof pages_blocks_cta;
  pages_blocks_text_block_paragraphs: typeof pages_blocks_text_block_paragraphs;
  pages_blocks_text_block: typeof pages_blocks_text_block;
  pages_blocks_rich_text: typeof pages_blocks_rich_text;
  pages_blocks_knowledgebase_index: typeof pages_blocks_knowledgebase_index;
  pages_blocks_file_download: typeof pages_blocks_file_download;
  pages_blocks_quick_stats_stats: typeof pages_blocks_quick_stats_stats;
  pages_blocks_quick_stats: typeof pages_blocks_quick_stats;
  pages_blocks_detail_stat_lines: typeof pages_blocks_detail_stat_lines;
  pages_blocks_detail_stat: typeof pages_blocks_detail_stat;
  pages_blocks_specs_table_tabs_rows: typeof pages_blocks_specs_table_tabs_rows;
  pages_blocks_specs_table_tabs: typeof pages_blocks_specs_table_tabs;
  pages_blocks_specs_table: typeof pages_blocks_specs_table;
  pages_blocks_cta_container_paragraphs: typeof pages_blocks_cta_container_paragraphs;
  pages_blocks_cta_container_ctas: typeof pages_blocks_cta_container_ctas;
  pages_blocks_cta_container: typeof pages_blocks_cta_container;
  pages: typeof pages;
  media: typeof media;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_nav_links: typeof site_settings_nav_links;
  site_settings_footer_columns_links: typeof site_settings_footer_columns_links;
  site_settings_footer_columns: typeof site_settings_footer_columns;
  site_settings: typeof site_settings;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero;
  relations_pages_blocks_single_image: typeof relations_pages_blocks_single_image;
  relations_pages_blocks_photo_carousel_images: typeof relations_pages_blocks_photo_carousel_images;
  relations_pages_blocks_photo_carousel: typeof relations_pages_blocks_photo_carousel;
  relations_pages_blocks_cta_ctas: typeof relations_pages_blocks_cta_ctas;
  relations_pages_blocks_cta: typeof relations_pages_blocks_cta;
  relations_pages_blocks_text_block_paragraphs: typeof relations_pages_blocks_text_block_paragraphs;
  relations_pages_blocks_text_block: typeof relations_pages_blocks_text_block;
  relations_pages_blocks_rich_text: typeof relations_pages_blocks_rich_text;
  relations_pages_blocks_knowledgebase_index: typeof relations_pages_blocks_knowledgebase_index;
  relations_pages_blocks_file_download: typeof relations_pages_blocks_file_download;
  relations_pages_blocks_quick_stats_stats: typeof relations_pages_blocks_quick_stats_stats;
  relations_pages_blocks_quick_stats: typeof relations_pages_blocks_quick_stats;
  relations_pages_blocks_detail_stat_lines: typeof relations_pages_blocks_detail_stat_lines;
  relations_pages_blocks_detail_stat: typeof relations_pages_blocks_detail_stat;
  relations_pages_blocks_specs_table_tabs_rows: typeof relations_pages_blocks_specs_table_tabs_rows;
  relations_pages_blocks_specs_table_tabs: typeof relations_pages_blocks_specs_table_tabs;
  relations_pages_blocks_specs_table: typeof relations_pages_blocks_specs_table;
  relations_pages_blocks_cta_container_paragraphs: typeof relations_pages_blocks_cta_container_paragraphs;
  relations_pages_blocks_cta_container_ctas: typeof relations_pages_blocks_cta_container_ctas;
  relations_pages_blocks_cta_container: typeof relations_pages_blocks_cta_container;
  relations_pages: typeof relations_pages;
  relations_media: typeof relations_media;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_nav_links: typeof relations_site_settings_nav_links;
  relations_site_settings_footer_columns_links: typeof relations_site_settings_footer_columns_links;
  relations_site_settings_footer_columns: typeof relations_site_settings_footer_columns;
  relations_site_settings: typeof relations_site_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
