/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal title used to organise pages in the CMS.
   */
  title: string;
  /**
   * Public URL path. Required for normal pages. Knowledgebase pages may leave this blank to derive the URL from their parent and knowledgebase label.
   */
  path?: string | null;
  showNavigation?: boolean | null;
  showInNav?: boolean | null;
  /**
   * Optional label used in the navigation. Falls back to the page title.
   */
  navLabel?: string | null;
  navOrder?: number | null;
  /**
   * Knowledgebase pages appear in knowledgebase indexes and use the wide article layout.
   */
  isKnowledgebasePage?: boolean | null;
  /**
   * Optional index label and URL segment. Falls back to the page title.
   */
  knowledgebaseLabel?: string | null;
  /**
   * Optional summary shown on standalone knowledgebase indexes.
   */
  knowledgebaseDescription?: string | null;
  /**
   * Optional parent page used to build the visual hierarchy in the knowledgebase index.
   */
  knowledgebaseParent?: (number | null) | Page;
  knowledgebaseOrder?: number | null;
  layout: (
    | {
        titlePrimary: string;
        titleSecondary: string;
        tagline?: string | null;
        subtagline?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        image: number | Media;
        constrainWidth?: boolean | null;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'singleImage';
      }
    | {
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        caption?: string | null;
        constrainWidth?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'photoCarousel';
      }
    | {
        ctas?:
          | {
              label: string;
              url: string;
              variant: 'primary' | 'secondary';
              icon: 'none' | 'externalLink' | 'discord' | 'terminal';
              id?: string | null;
            }[]
          | null;
        align: 'center' | 'left';
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        heading?: string | null;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textBlock';
      }
    | {
        /**
         * Rich knowledgebase content with headings, inline links, inline code, lists, and code blocks.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading?: string | null;
        /**
         * Optional intro copy for standalone knowledgebase index pages.
         */
        intro?: string | null;
        variant: 'standalone' | 'sidebar';
        id?: string | null;
        blockName?: string | null;
        blockType: 'knowledgebaseIndex';
      }
    | {
        /**
         * Absolute URL for the externally hosted file.
         */
        url: string;
        description: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fileDownload';
      }
    | {
        stats?:
          | {
              icon:
                | 'Antenna'
                | 'Battery'
                | 'Bluetooth'
                | 'Camera'
                | 'Cpu'
                | 'EthernetPort'
                | 'ExternalLink'
                | 'Gamepad2'
                | 'Gpu'
                | 'HardDrive'
                | 'Heart'
                | 'Keyboard'
                | 'MemoryStick'
                | 'Radio'
                | 'Terminal'
                | 'Usb'
                | 'Wifi'
                | 'Zap';
              color: 'cyan' | 'blue' | 'purple' | 'green' | 'yellow' | 'orange' | 'red' | 'pink';
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quickStats';
      }
    | {
        icon?:
          | (
              | 'Antenna'
              | 'Battery'
              | 'Bluetooth'
              | 'Camera'
              | 'Cpu'
              | 'EthernetPort'
              | 'ExternalLink'
              | 'Gamepad2'
              | 'Gpu'
              | 'HardDrive'
              | 'Heart'
              | 'Keyboard'
              | 'MemoryStick'
              | 'Radio'
              | 'Terminal'
              | 'Usb'
              | 'Wifi'
              | 'Zap'
            )
          | null;
        color?: ('cyan' | 'blue' | 'purple' | 'green' | 'yellow' | 'orange' | 'red' | 'pink') | null;
        lines?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'detailStat';
      }
    | {
        heading?: string | null;
        tabs?:
          | {
              label: string;
              title: string;
              rows?:
                | {
                    label: string;
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'specsTable';
      }
    | {
        title: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctas?:
          | {
              label: string;
              url: string;
              variant: 'primary' | 'secondary';
              icon: 'none' | 'externalLink' | 'discord' | 'terminal';
              id?: string | null;
            }[]
          | null;
        subtext?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaContainer';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text shown to screen readers and used while the image loads
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  showNavigation?: T;
  showInNav?: T;
  navLabel?: T;
  navOrder?: T;
  isKnowledgebasePage?: T;
  knowledgebaseLabel?: T;
  knowledgebaseDescription?: T;
  knowledgebaseParent?: T;
  knowledgebaseOrder?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              titlePrimary?: T;
              titleSecondary?: T;
              tagline?: T;
              subtagline?: T;
              id?: T;
              blockName?: T;
            };
        singleImage?:
          | T
          | {
              image?: T;
              constrainWidth?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        photoCarousel?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              caption?: T;
              constrainWidth?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              align?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        knowledgebaseIndex?:
          | T
          | {
              heading?: T;
              intro?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        fileDownload?:
          | T
          | {
              url?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        quickStats?:
          | T
          | {
              stats?:
                | T
                | {
                    icon?: T;
                    color?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        detailStat?:
          | T
          | {
              icon?: T;
              color?: T;
              lines?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specsTable?:
          | T
          | {
              heading?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    title?: T;
                    rows?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaContainer?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    icon?: T;
                    id?: T;
                  };
              subtext?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  navBrandLabel?: string | null;
  /**
   * Turn this on while editing across local and Vercel so frontend pages read fresh CMS data on every request.
   */
  disablePageCache?: boolean | null;
  /**
   * Optional links shown after CMS-managed page links. Useful for external links.
   */
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLine1?: string | null;
  footerLine2?: string | null;
  /**
   * Optional site-wide footer link columns.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navBrandLabel?: T;
  disablePageCache?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLine1?: T;
  footerLine2?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}